apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: fadygamil/server:latest
        ports:
        - containerPort: 8081
        env:
        - name: REDIS_URL
          value: "redis:6379"
        - name: PORT
          value: "8081"
---
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  selector:
    app: server
  ports:
  - port: 8081
    targetPort: 8081